output "s3_bucket_name" {
  description = "The name of the S3 bucket where you will sync your Next.js out/ directory"
  value       = aws_s3_bucket.admin_panel.id
}

output "cloudfront_distribution_id" {
  description = "The ID of the CloudFront distribution"
  value       = aws_cloudfront_distribution.admin_panel.id
}

output "cloudfront_domain_name" {
  description = "The domain name generated by CloudFront (e.g., xxx.cloudfront.net)"
  value       = aws_cloudfront_distribution.admin_panel.domain_name
}
