export interface SupportAuditLog {
  id: string;
  agentId: string;
  action: AuditAction;
  targetType: TargetType;
  targetId: string;
  oldValue: Record<string, any> | null;
  newValue: Record<string, any> | null;
  timestamp: string;
  agentName?: string;
}

export const TARGET_TYPES = {
  TICKET: 'TICKET',
  ARTICLE: 'ARTICLE',
  USER: 'USER',
  AGENT: 'AGENT',
  ENQUIRY: 'ENQUIRY',
  CATEGORY: 'CATEGORY',
  TAG: 'TAG'
} as const;

export type TargetType = typeof TARGET_TYPES[keyof typeof TARGET_TYPES];

export const AUDIT_ACTIONS = {
  // Ticket Actions
  TICKET_CREATED: 'TICKET_CREATED',
  TICKET_UPDATED: 'TICKET_UPDATED',
  TICKET_DELETED: 'TICKET_DELETED',
  TICKET_STATUS_CHANGE: 'TICKET_STATUS_CHANGE',
  TICKET_PRIORITY_CHANGE: 'TICKET_PRIORITY_CHANGE',
  TICKET_CATEGORY_CHANGE: 'TICKET_CATEGORY_CHANGE',
  TICKET_ASSIGNED: 'TICKET_ASSIGNED',
  TICKET_UNASSIGNED: 'TICKET_UNASSIGNED',
  TICKET_MERGE: 'TICKET_MERGE',
  TICKET_SPLIT: 'TICKET_SPLIT',
  TICKET_NOTE_ADDED: 'TICKET_NOTE_ADDED',
  TICKET_ATTACHMENT_ADDED: 'TICKET_ATTACHMENT_ADDED',
  TICKET_ATTACHMENT_REMOVED: 'TICKET_ATTACHMENT_REMOVED',
  
  // Article Actions
  ARTICLE_CREATED: 'ARTICLE_CREATED',
  ARTICLE_UPDATED: 'ARTICLE_UPDATED',
  ARTICLE_DELETED: 'ARTICLE_DELETED',
  ARTICLE_PUBLISHED: 'ARTICLE_PUBLISHED',
  ARTICLE_ARCHIVED: 'ARTICLE_ARCHIVED',
  ARTICLE_CATEGORY_CHANGE: 'ARTICLE_CATEGORY_CHANGE',
  ARTICLE_TAG_ADDED: 'ARTICLE_TAG_ADDED',
  ARTICLE_TAG_REMOVED: 'ARTICLE_TAG_REMOVED',
  
  // User Actions
  USER_CREATED: 'USER_CREATED',
  USER_UPDATED: 'USER_UPDATED',
  USER_DELETED: 'USER_DELETED',
  USER_ROLE_CHANGE: 'USER_ROLE_CHANGE',
  USER_STATUS_CHANGE: 'USER_STATUS_CHANGE',
  USER_PASSWORD_RESET: 'USER_PASSWORD_RESET',
  
  // Agent Actions
  AGENT_CREATED: 'AGENT_CREATED',
  AGENT_UPDATED: 'AGENT_UPDATED',
  AGENT_DELETED: 'AGENT_DELETED',
  AGENT_STATUS_CHANGE: 'AGENT_STATUS_CHANGE',
  AGENT_DEPARTMENT_CHANGE: 'AGENT_DEPARTMENT_CHANGE',
  
  // Enquiry Actions
  ENQUIRY_CREATED: 'ENQUIRY_CREATED',
  ENQUIRY_UPDATED: 'ENQUIRY_UPDATED',
  ENQUIRY_DELETED: 'ENQUIRY_DELETED',
  ENQUIRY_STATUS_CHANGE: 'ENQUIRY_STATUS_CHANGE',
  ENQUIRY_ASSIGNED: 'ENQUIRY_ASSIGNED',
  
  // Category Actions
  CATEGORY_CREATED: 'CATEGORY_CREATED',
  CATEGORY_UPDATED: 'CATEGORY_UPDATED',
  CATEGORY_DELETED: 'CATEGORY_DELETED',
  
  // Tag Actions
  TAG_CREATED: 'TAG_CREATED',
  TAG_UPDATED: 'TAG_UPDATED',
  TAG_DELETED: 'TAG_DELETED',
  
  // System Actions
  AGENT_LOGIN: 'AGENT_LOGIN',
  AGENT_LOGOUT: 'AGENT_LOGOUT',
  SYSTEM_BACKUP: 'SYSTEM_BACKUP',
  SYSTEM_MAINTENANCE: 'SYSTEM_MAINTENANCE',
  BULK_OPERATION: 'BULK_OPERATION'
} as const;

export type AuditAction = typeof AUDIT_ACTIONS[keyof typeof AUDIT_ACTIONS];

export const AUDIT_ACTION_GROUPS = {
  TICKET_MANAGEMENT: [
    AUDIT_ACTIONS.TICKET_CREATED,
    AUDIT_ACTIONS.TICKET_UPDATED,
    AUDIT_ACTIONS.TICKET_DELETED,
    AUDIT_ACTIONS.TICKET_STATUS_CHANGE,
    AUDIT_ACTIONS.TICKET_PRIORITY_CHANGE,
    AUDIT_ACTIONS.TICKET_CATEGORY_CHANGE,
    AUDIT_ACTIONS.TICKET_ASSIGNED,
    AUDIT_ACTIONS.TICKET_UNASSIGNED,
    AUDIT_ACTIONS.TICKET_MERGE,
    AUDIT_ACTIONS.TICKET_SPLIT,
    AUDIT_ACTIONS.TICKET_NOTE_ADDED,
    AUDIT_ACTIONS.TICKET_ATTACHMENT_ADDED,
    AUDIT_ACTIONS.TICKET_ATTACHMENT_REMOVED
  ],
  ARTICLE_MANAGEMENT: [
    AUDIT_ACTIONS.ARTICLE_CREATED,
    AUDIT_ACTIONS.ARTICLE_UPDATED,
    AUDIT_ACTIONS.ARTICLE_DELETED,
    AUDIT_ACTIONS.ARTICLE_PUBLISHED,
    AUDIT_ACTIONS.ARTICLE_ARCHIVED,
    AUDIT_ACTIONS.ARTICLE_CATEGORY_CHANGE,
    AUDIT_ACTIONS.ARTICLE_TAG_ADDED,
    AUDIT_ACTIONS.ARTICLE_TAG_REMOVED
  ],
  USER_MANAGEMENT: [
    AUDIT_ACTIONS.USER_CREATED,
    AUDIT_ACTIONS.USER_UPDATED,
    AUDIT_ACTIONS.USER_DELETED,
    AUDIT_ACTIONS.USER_ROLE_CHANGE,
    AUDIT_ACTIONS.USER_STATUS_CHANGE,
    AUDIT_ACTIONS.USER_PASSWORD_RESET
  ],
  AGENT_MANAGEMENT: [
    AUDIT_ACTIONS.AGENT_CREATED,
    AUDIT_ACTIONS.AGENT_UPDATED,
    AUDIT_ACTIONS.AGENT_DELETED,
    AUDIT_ACTIONS.AGENT_STATUS_CHANGE,
    AUDIT_ACTIONS.AGENT_DEPARTMENT_CHANGE
  ],
  SYSTEM_OPERATIONS: [
    AUDIT_ACTIONS.AGENT_LOGIN,
    AUDIT_ACTIONS.AGENT_LOGOUT,
    AUDIT_ACTIONS.SYSTEM_BACKUP,
    AUDIT_ACTIONS.SYSTEM_MAINTENANCE,
    AUDIT_ACTIONS.BULK_OPERATION
  ]
} as const;

export interface AuditLogFilters {
  targetTypes?: TargetType[];
  actions?: AuditAction[];
  agentIds?: string[];
  dateRange?: {
    from: string;
    to: string;
  };
  search?: string;
}
